services:
    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: mysql-crud-service
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: crud_post
            MYSQL_USER: crud_user
            MYSQL_PASSWORD: crud_password
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - crud-network
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

    # phpMyAdmin (Optional - MySQL GUI)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-crud-service
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: crud_user
            PMA_PASSWORD: crud_password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - '8080:80'
        depends_on:
            - mysql
        networks:
            - crud-network

volumes:
    mysql_data:
        driver: local

networks:
    crud-network:
        driver: bridge
