import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainContainer from "@/containers/layouts/MainContainer";
import Header from "@/containers/layouts/header";
import ContentAnimation from "@/containers/layouts/content-animation";
import Footer from "@/containers/layouts/footer";
import { QueryProvider } from "./providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={''}
      >
        <MainContainer>

          <div className="main-content flex min-h-screen flex-col">
            {/* BEGIN TOP NAVBAR */}
            <Header />
            {/* END TOP NAVBAR */}

            {/* BEGIN CONTENT AREA */}
            <QueryProvider><ContentAnimation>{children}</ContentAnimation></QueryProvider>
            {/* END CONTENT AREA */}

            {/* BEGIN FOOTER */}
            <Footer />
            {/* END FOOTER */}

          </div>
        </MainContainer>
      </body>
    </html>
  );
}
